name: Docker Build and Push

on: push

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Build Image
      uses: docker/build-action@v2
      with:
        context: ./
        file: ./Dockerfile

  Push:
    name: Docker Push
    runs-on: ubuntu-latest
    steps:
    - name: Get Datetime
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H-%M-%S')"
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Docker Push
      uses: docker/push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/website:${{ steps.date.outputs.date }}

